### PR TITLE
hovering effect added to buttons

### PR DESCRIPTION
**Pull request by supsa-ak**
Solved issue #2. Please add 'hacktoberfest-accepted' label to this PR and Merge it.

### CODE REVIEW

**Comment by supsa-ak** [comment]
Please add 'hacktoberfest-accepted' label to this PR.

**Comment by supsa-ak** [comment]
==Urgent== 
Hi, Please add 'hacktoberfest-accepted' label to this PR as it is last date for hacktoberfest.

**Comment by Lensco825** [comment]
@supsa-ak  Please quickly tell me if this is the right way to add the label! I'll also try to add this too the repo itself at 11 this morning.

**Comment by supsa-ak** [comment]
If you want to participate this repository in Hacktoberfest then add topic  'hacktoberfest' to this repo .

If repository does not have topic 'hacktoberfest' then Pull Request must be 'hacktoberfest-accepted' label on it by maintainer to participate.

**Comment by Lensco825** [comment]
it should be on the repo too now, thanks for participating!.

image

**Pull request merged**
